apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  labels:
    env: dev
    app: myapp-svc
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30005
  selector:
      app: myapp
      type: frontend-pod
    