apiVersion: apps/v1
kind: Deployment
metadata:
   name: hello-world-app-deploy
   labels:
      name: hello-world-app-deploy
      app: hello-world-app
spec:
   replicas: 1
   template:
       metadata:
          name: hello-world-app-pod
          labels: 
             name: hello-world-app-pod
             app: hello-world-app
             type: frontend
       spec: 
         containers: 
            - name:  hello-world-app-container
              image:  vsiraparapu/hello-world:latest
              ports: 
                - containerPort: 8080
           
   selector:
      matchLabels:
          name: hello-world-app-pod
          app: hello-world-app
          type: frontend