apiVersion: v1
kind: Service
metadata:
   name: hello-world-app-svc
   labels: 
     name: hello-world-app-svc
     app: hello-world-app
spec: 
  type: NodePort
  ports:
   - targetPort: 8080
     port: 8080
     nodePort: 30008
  selector:
    name: hello-world-app-pod
    app: hello-world-app
    type: frontend
