apiVersion: apps/v1
kind: Deployment
metadata:
spec:
   template:
      metadata:
         name: myapp-pod
         labels:
           env: dev
           type: frontend
      spec:
        containers:
          - name: myapp-container
            image: myapp:v2
   replicas: 3
   selector:
     matchLabels: 
           env: dev
           type: frontend
      
