apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: nginx-rs
    labels:
       app: nginx-app
       type: frontend-app
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: frontend-pod
    spec: 
      containers:
         - name: mynginx-container
           image: nginx
  replicas: 3
  selector: 
     matchLabels:
        app:  myapp
        type: frontend-pod
         