apiVersion: v1
kind: ReplicationController
metadata:
    name: nginx-rc
    labels:
       app: nginx-app
       type: frontend-app
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: frontend-pod
    spec: 
      containers:
         - name: mynginx-container
           image: nginx
  replicas: 3